### ISSUE TITLE
Can't start Blokada

### ISSUE THREAD

**Issue by Pitel** [blokadaorg/blokada#528]
### Steps to reproduce
1. Try to start Blokada

### Expected behaviour
Blokada starts

### Actual behaviour
Blokada exits immediately

### Configuration
1. Blokada version
v4.3.5

2. Device model
Pixel 3A

3. Android version / ROM
Q

### Questions
1. How long have you been using Blokada? 
Couple of months.

2. How long time ago has the problem started to happen? 
Today.

3.  How often does this problem happen to you?
Always.

```
    java.lang.RuntimeException: Couldn't create Paper dir: /storage/emulated/0/Download/blokada/io.paperdb
        at io.paperdb.DbStoragePlainFile.createPaperDir(DbStoragePlainFile.java:325)
        at io.paperdb.DbStoragePlainFile.assertInit(DbStoragePlainFile.java:316)
        at io.paperdb.DbStoragePlainFile.select(DbStoragePlainFile.java:143)
        at io.paperdb.Book.read(Book.java:73)
        at io.paperdb.Book.read(Book.java:58)
        at core.PaperSource.get(NewPersistence.kt:18)
        at core.Register$get$2$1.invoke(NewPersistence.kt:104)
        at core.Register$get$2.invoke(NewPersistence.kt:101)
        at core.Register.get(NewPersistence.kt:99)
        at core.Register.get$default(NewPersistence.kt:99)
        at core.NewPersistenceKt.get(NewPersistence.kt:144)
        at core.DnsImpl$dnsServers$1.invoke(Dns.kt:105)
        at core.DnsImpl$dnsServers$1.invoke(Dns.kt:42)
        at gs.property.BaseProperty$refresh$1.invoke(Property.kt:306)
        at gs.property.BaseProperty$refresh$1.invoke(Property.kt:212)
        at nl.komponents.kovenant.TaskPromise$wrapper$1.invoke(promises-jvm.kt:138)
        at nl.komponents.kovenant.TaskPromise$wrapper$1.invoke(promises-jvm.kt:130)
        at nl.komponents.kovenant.NonBlockingDispatcher$ThreadContext.run(dispatcher-jvm.kt:327)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by rpeter85** [comment]
Grant storage permission for Blokada.
The exception says it couldn't persist its database on the storage device.

**Comment by Pitel** [comment]
Cool, it helped. But maybe Blokada should ask for the permission and not crash.

**Comment by rpeter85** [comment]
It asks for storage permission.
