### ISSUE TITLE
Unable to access Blokada website from Russia

### ISSUE THREAD

**Issue by JohnVillalovos** [blokadaorg/blokada#648]
Unable to access the Blokada website from Russia.

This seems to be preventing my phone from being able to download the Ad block lists. Though not 100% sure if that is the case or not.

I see this in my log file:
```
02-14 11:50:20.234 V b4:gscore-workerX-13 checking for announcement    
02-14 11:50:20.235 E b4:gscore-workerX-13 failed fetching announcement    java.io.IOException: Cleartext HTTP traffic to localhost not permitted
java.io.IOException: Cleartext HTTP traffic to localhost not permitted
	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at core.InputOutputKt$createStream$1.invoke(InputOutput.kt:72)
	at core.InputOutputKt$createStream$1.invoke(Unknown Source:0)
	at core.InputOutputKt.createStream(InputOutput.kt:66)
	at core.InputOutputKt.loadAsString(InputOutput.kt:54)
	at core.BlokadaRestKt.requestAnnouncement(BlokadaRest.kt:90)
	at core.BlokadaRestKt.maybeCheckForAnnouncement(BlokadaRest.kt:34)
	at core.TunnelKt$newTunnelModule$1$3$19.invoke(Tunnel.kt:319)
	at core.TunnelKt$newTunnelModule$1$3$19.invoke(Unknown Source:0)
	at gs.property.When$execute$3.invoke(Property.kt:169)
	at gs.property.When$execute$3.invoke(Property.kt:146)
	at nl.komponents.kovenant.TaskPromise$wrapper$1.invoke(promises-jvm.kt:138)
	at nl.komponents.kovenant.TaskPromise$wrapper$1.invoke(promises-jvm.kt:130)
	at nl.komponents.kovenant.NonBlockingDispatcher$ThreadContext.run(dispatcher-jvm.kt:327)
	at java.lang.Thread.run(Thread.java:919)
02-14 11:52:58.902 V b4:gscore-workerX-15 checking for announcement    
02-14 11:52:58.903 E b4:gscore-workerX-15 failed fetching announcement    java.io.IOException: Cleartext HTTP traffic to localhost not permitted
java.io.IOException: Cleartext HTTP traffic to localhost not permitted
	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at core.InputOutputKt$createStream$1.invoke(InputOutput.kt:72)
	at core.InputOutputKt$createStream$1.invoke(Unknown Source:0)
	at core.InputOutputKt.createStream(InputOutput.kt:66)
	at core.InputOutputKt.loadAsString(InputOutput.kt:54)
	at core.BlokadaRestKt.requestAnnouncement(BlokadaRest.kt:90)
	at core.BlokadaRestKt.maybeCheckForAnnouncement(BlokadaRest.kt:34)
	at core.TunnelKt$newTunnelModule$1$3$19.invoke(Tunnel.kt:319)
	at core.TunnelKt$newTunnelModule$1$3$19.invoke(Unknown Source:0)
	at gs.property.When$execute$3.invoke(Property.kt:169)
	at gs.property.When$execute$3.invoke(Property.kt:146)
	at nl.komponents.kovenant.TaskPromise$wrapper$1.invoke(promises-jvm.kt:138)
	at nl.komponents.kovenant.TaskPromise$wrapper$1.invoke(promises-jvm.kt:130)
	at nl.komponents.kovenant.NonBlockingDispatcher$ThreadContext.run(dispatcher-jvm.kt:327)
	at java.lang.Thread.run(Thread.java:919)
02-14 11:53:25.072 V b4:entrypoint onInvalidateFilters    
02-14 11:53:25.073 V b4:entrypoint syncing after recent changes    
02-14 11:53:25.073 V b4:tunnel-main invalidating filters    
02-14 11:53:25.073 V b4:tunnel-main invalidating filters cache    
02-14 11:53:25.074 V b4:tunnel-main >> syncing tunnel overall state    
02-14 11:53:25.074 V b4:tunnel-main syncing filters    
02-14 11:53:25.075 W b4:tunnel-main no filters url set, will skip syncing filters    
02-14 11:53:25.076 V b4:tunnel-main actually setting vpn tunnel    
02-14 11:53:25.077 V b4:tunnel-main tunnel already in proposed state, doing nothing    CurrentTunnel(dnsServers=[/1.1.1.1:53, /8.8.8.8:53, /8.8.4.4:53, /1.0.0.1:53], adblocking=true, blockaVpn=false, lease=CurrentLease(gatewayId=, gatewayIp=, gatewayPort=0, gatewayNiceName=, vip4=, vip6=, leaseActiveUntil=Thu Jan 01 03:00:00 GMT+03:00 1970, leaseOk=false, migration=1))
02-14 11:53:25.077 V b4:tunnel-main done syncing    
```

**Comment by peterroth** [comment]
Blokada's website is hosted on GitHub, where you just reported the issue. Can you check if you can access [Cloudflare](https://www.cloudflare.com/) (the DNS provider in our case).

**Comment by JohnVillalovos** [comment]
When I connect to https://blokada.org/ from Russia I get error message: "Unable to connect"

If I route my connection through a US based server I can connect. I am doing this on my PC.

So it might be nice if turned off blocking off Russian IP addresses on Cloudflare for https://blokada.org/

But unsure if my theory is correct that the Blokada app is trying to connect to https://blokada.org/ to download ad block files. If so, then that would explain why my app does not seem to be able to retrieve the ad block files.

Thanks.

**Comment by peterroth** [comment]
Thanks for the test.
There are no restrictions from Blokada side for countries, regions or anything else, but we will contact Cloudflare if they know about such a misbehaviour.

**Comment by JohnVillalovos** [comment]
> we will contact Cloudflare if they know about such a misbehaviour.

Thank you!

**Comment by l1bbcsg** [comment]
I'm having the same problem.

blokada.org resolves to `104.31.75.217` and this particular address is blocked in Russia as per decision 2-946/13 of Stavropol district court in 2013. The decision involved some gambling business and was meant to block their site.

And yes, they blocked a random CDN IP (probably at subnet level too) and that hit some clueless unrelated site. This is the unfortunate reality of technical illiteracy in Russian government.

I don't know how Cloudflare assigns IPs to domains. If it's static, then blokada.org won't be accessible from most Russian ISPs. If it's dynamic, then it won't be accessible from most Russian ISPs randomly.

Accessing the site is trivial enough with a VPN, but downloading lists from the app not so much.

Not sure what you can do about it, but at least here's the source of the problem.
