### ISSUE TITLE
Blokada 5 blocks all traffic when DHCP-set DNS is mandatory

### ISSUE THREAD

**Issue by szotsaki** [blokadaorg/blokada#822]
On public networks with DHCP come sometimes mandatory DNS settings. Ignoring those means that the internet connections is not functional anymore.

As soon as I connect to such a network, mail checking, web browsing stop when using Blokada 5.6.0. In the moment I turn off Blokada, everything starts to work again.

Even Blokada itself fails to connect to the network:
```
13:25:33.927   DnsMapper  Using DNS configuration [DoH/PlusMode: false/false]: Dns(id=cloudflare.malware, ips=[1.1.1.2, 1.0.0.2, 2606:4700:4700::1112, 2606:4700:4700::1002], plusIps=null, port=null, name=null, path=null, label=Cloudflare: malware blocking, canUseInCleartext=true)
13:25:33.929   SystemTunn Received a request to open tunnel
13:25:33.930   SystemTunn Tunnel turnOn() called
13:25:33.931   STConfigur Configuring VPN for Libre mode
13:25:33.932   STConfigur Using IP: 203.0.113.69
13:25:33.933   STConfigur Using IPv6: 2001:db8:0:0:0:0:0:0
13:25:33.934   STConfigur Adding DNS server: 1.1.1.2
13:25:33.934   STConfigur Adding mapped DNS server for IPv4
13:25:33.937   STConfigur Adding DNS server: 1.0.0.2
13:25:33.937   STConfigur Adding mapped DNS server for IPv4
13:25:33.938   STConfigur Setting MTU: 1280
13:25:33.938   STConfigur Setting bypass for 33 apps
13:25:33.962   SystemTunn Asking system for tunnel
13:25:33.982   PacketLoop Requested to start packet loop (libre mode)
13:25:33.995   Metrics    Started metrics
13:25:33.995   PLLibre    Started packet loop thread: 195939459
13:25:34.045   Settings   Marking first time as seen
13:25:34.060   Blocka     Tunnel started successfully
13:25:34.122   SystemTunn Bound SystemTunnel
13:25:34.233   Metrics    DNS-RTT/DNS-ERR/REC-ERR: 91ms/0/0
13:25:36.189   Metrics    DNS-RTT/DNS-ERR/REC-ERR: 116ms/0/0
13:25:38.165   SystemTunn Unbinding SystemTunnel
13:25:38.175   SystemTunn unbindService called
13:25:46.062   Blocklist  Removing blocklist file for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
13:25:46.063   Blocklist  Removing blocklist file for: https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt
13:25:46.064   Blocklist  Removing blocklist file for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
13:25:46.066   Blocklist  Removing blocklist file for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
13:25:46.067   Blocklist  Removing blocklist file for: https://blokada.org/mirror/v5/ddgtrackerradar/standard/hosts.txt
13:25:46.068 E Pack       Could not install pack: Could not fetch domains for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
model.BlokadaException: Could not fetch domains for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
	at service.BlocklistService.download(BlocklistService.kt:172)
	at service.BlocklistService$downloadAll$2$1.invokeSuspend(BlocklistService.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

13:25:46.072   Blocklist  Removing blocklist file for: https://blokada.org/mirror/v5/ddgtrackerradar/standard/hosts.txt
13:25:46.142 E Pack       Could not install pack: Could not fetch domains for: https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt
model.BlokadaException: Could not fetch domains for: https://blokada.org/mirror/v5/exodusprivacy/standard/hosts.txt
	at service.BlocklistService.download(BlocklistService.kt:172)
	at service.BlocklistService$downloadAll$2$1.invokeSuspend(BlocklistService.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: model.BlokadaException: Could not fetch domains for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
		... 8 more
	Suppressed: model.BlokadaException: Could not fetch domains for: https://blokada.org/mirror/v5/ddgtrackerradar/standard/hosts.txt
		... 8 more

13:25:46.167 W Dialog     Ignoring new dialog request, one is already being displayed
13:25:46.171 E Pack       Could not install pack: Could not fetch domains for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
model.BlokadaException: Could not fetch domains for: https://blokada.org/mirror/v5/energized/blu/hosts.txt
	at service.BlocklistService.download(BlocklistService.kt:172)
	at service.BlocklistService$downloadAll$2$1.invokeSuspend(BlocklistService.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: model.BlokadaException: Could not fetch domains for: https://blokada.org/mirror/v5/ddgtrackerradar/standard/hosts.txt
		... 8 more

13:25:46.193 W Dialog     Ignoring new dialog request, one is already being displayed
13:26:13.935 W Account    Could not create account: Api request failed
```

Other applications fail with messages like:
* Unable to resolve host "...."
* `android_getaddrinfo` failed: `EAI_NODATA` (No address associated with hostname)

Similar threads in the support forum:
* https://community.blokada.org/t/blokada-ignores-dhcp-supplied-dns-server/8813
* https://community.blokada.org/t/please-add-network-dependency-for-dns-setting/9299
* https://community.blokada.org/t/how-to-setup-blokada-5-to-use-default-dns-from-the-internet-provider/5102

**Comment by peterroth** [comment]
In Blokada 5.7 (currently in beta phase) you'll have the ability to use the system provided DNS. It's on the Advanced screen - Networks.

**Comment by szotsaki** [comment]
That's good news, thank you for the development!

**Comment by peterroth** [comment]
Hi,
Version 5.7 released today, you can choose to prefer network provided DNS.
