### ISSUE TITLE
Crash when click on certain options which depends on WebView (WebView uninstalled)

### ISSUE THREAD

**Issue by shuvashish76** [blokadaorg/blokada#891]
For more info plz check https://github.com/MuntashirAkon/AppManager/issues/566

**Crash log**

FATAL EXCEPTION: main
Process: org.blokada.alarm, PID: 13778
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.blokada.alarm/ui.StaticUrlWebActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at gs.presentation.WebDash.createView(WebViewActor.kt:73)
	at ui.AbstractWebActivity.onCreate(AbstractWebActivity.kt:59)
	at ui.StaticUrlWebActivity.onCreate(StaticUrlWebActivity.kt:19)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:423)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
	at android.webkit.WebView.getFactory(WebView.java:2530)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2525)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2590)
	at android.view.View.<init>(View.java:4574)
	at android.view.View.<init>(View.java:4706)
	at android.view.ViewGroup.<init>(ViewGroup.java:597)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
	at android.webkit.WebView.<init>(WebView.java:643)
	at android.webkit.WebView.<init>(WebView.java:588)
	at android.webkit.WebView.<init>(WebView.java:571)
	at android.webkit.WebView.<init>(WebView.java:558)
	... 27 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:319)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
	... 39 more

**Comment by djangooffchain** [comment]
Well you have no WebView which is not "normal" on Android. There is a setting in Settings -> This device, which allows you to select to open links in the external browser instead, you should enable it.

**Comment by kar** [comment]
There is a setting in Settings -> This device, which allows you to select to open links in the external browser instead, you should enable it.
